export const PATHS = {
  home: "/",
  intro: "/introduction",
  cheatsheet: "/cheatsheet",
  begin: {
    variables: `/begin/variables`,
    types: `/begin/types`,
    functions: `/begin/functions`,
    events: `/begin/events`,
    objects: `/begin/objects`,
    arrays: `/begin/arrays`,
    tips: `/begin/tips`,
    examples: `/begin/examples`,
    exercises: `/begin/exercises`,
    conditions: `/intermediate/conditions`,
    loops: "/begin/loops",
    arrayFunctions: "/begin/array-functions",
    objectFunctions: "/begin/object-functions",
    form: "/begin/form",
  },
  intermediate: {
    asyncAwait: "/intermediate/async-await",
    promises: "/intermediate/promises",
    fetch: "/intermediate/fetch",
    storages: "/intermediate/storages",
    exercises: `/intermediate/exercises`,
    tips: "/intermediate/tips",
  },
  jquery: "/jquery",
}
