export const PATHS = {
  home: "/",
  css: {
    recap: "/mmi2/css/recap",
    flex: "/mmi2/css/flex",
    grid: "/mmi2/css/grid",
  },
  php: {
    php: "/mmi2/php/phpsql",
  },
  js: {
    intro: "/mmi2/js",
    tp: "/mmi2/js/tp",
    cheatsheet: "/cheatsheet",
    begin: {
      variables: `/mmi2/js/begin/variables`,
      types: `/mmi2/js/begin/types`,
      functions: `/mmi2/js/begin/functions`,
      events: `/mmi2/js/begin/events`,
      objects: `/mmi2/js/begin/objects`,
      arrays: `/mmi2/js/begin/arrays`,
      tips: `/mmi2/js/begin/tips`,
      examples: `/mmi2/js/begin/examples`,
      exercises: `/mmi2/js/begin/exercises`,
      conditions: `/mmi2/js/begin/conditions`,
      loops: "/mmi2/js/begin/loops",
      arrayFunctions: "/mmi2/js/begin/array-functions",
      objectFunctions: "/mmi2/js/begin/object-functions",
      form: "/mmi2/js/begin/form",
    },
    intermediate: {
      asyncAwait: "/mmi2/js/intermediate/async-await",
      promises: "/mmi2/js/intermediate/promises",
      fetch: "/mmi2/js/intermediate/fetch",
      storages: "/mmi2/js/intermediate/storages",
      exercises: `/mmi2/js/intermediate/exercises`,
      tips: "/mmi2/js/intermediate/tips",
    },
    jquery: "/mmi2/js/jquery",
  },
  mmi1: {
    intro: "/mmi1",
    TD_HTML5: "/mmi1/TD/HTML5",
  },
}
